name: AdvancedAnticheat
version: 1.0-SNAPSHOT
main: johan.anticheat.AdvancedAnticheat
api-version: "1.21"
authors: [Johan]
commands:
  anticheat:
    description: Opens staff GUI
    usage: /anticheat
    permission: anticheat.staff
permissions:
  anticheat.staff:
    default: op
  anticheat.alert:
    default: op
